language: python
python:
  - '3.6.9'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

script:
  - cd pur_beurre
  - ./manage.py test